CREATE TABLE ACCOUNT
 (ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  BALANCE DOUBLE,
  CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP);

CREATE TABLE TRANSFER
  (ID INT PRIMARY KEY,
  SOURCE_ACCOUNT_ID  INT,
  FOREIGN KEY(SOURCE_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  TARGET_ACCOUNT_ID  INT,
  FOREIGN KEY(TARGET_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  AMOUNT DOUBLE,-
  CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP);